"""add_category_model

Revision ID: 55e6c3d6df6b
Revises: df30575b5037
Create Date: 2025-09-25 23:24:48.913712

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55e6c3d6df6b'
down_revision: Union[str, Sequence[str], None] = 'df30575b5037'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'passport_series',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'passport_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'passport_number',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'passport_series',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
