services:

  web:
    build:
        context: ..
        dockerfile: docker/Dockerfile
    container_name: fastapi_app
    command: >
      /bin/sh -c "while ! nc -z postgres 5432; do sleep 1; done;
                  alembic upgrade head &&
                  uvicorn main:app --host 0.0.0.0 --port 8000 --workers 4"
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app/src
    env_file:
      - ../env/.env
    environment:
      - PYTHONPATH=/app/src
    depends_on:
      - postgres

  postgres:
    image: postgres:17.0
    container_name: fastapi_db
    env_file:
      - ../env/.env
    ports:
      - "5433:5432"
    volumes:
      - ./.volumes/pgdata:/var/lib/postgresql/data


networks:
  shared_network:
    driver: bridge