services:

  web:
    build:
        context: ..
        dockerfile: docker/Dockerfile
    container_name: finance_app
    ports:
      - "8000:8000"
    volumes:
      - ../src:/app/src
      - ../env/.env:/app/env/.env
    env_file:
      - ../env/.env
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - shared_network

  postgres:
    image: postgres:17.0
    container_name: finance_db
    env_file:
      - ../env/.env
    ports:
      - "5433:5432"
    volumes:
      - ./.volumes/pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - shared_network

networks:
  shared_network:
    driver: bridge