"""m2m_product_tags

Revision ID: 13c1196f2ebc
Revises: ccb837bd96f9
Create Date: 2025-09-26 15:16:58.386940

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13c1196f2ebc'
down_revision: Union[str, Sequence[str], None] = 'ccb837bd96f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_tag',
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('tag_id', sa.UUID(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.uuid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.uuid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('product_id', 'tag_id', 'uuid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product_tag')
    # ### end Alembic commands ###
