"""20251001_170139_modified_value

Revision ID: 26285028c53c
Revises: e85f43f97311
Create Date: 2025-10-01 22:01:40.221148

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26285028c53c'
down_revision: Union[str, Sequence[str], None] = 'e85f43f97311'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_tag',
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('tag_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.uuid'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.uuid'], ),
    sa.PrimaryKeyConstraint('product_id', 'tag_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product_tag')
    # ### end Alembic commands ###
