"""20250927_194212_add_produt_image_and_upload

Revision ID: b290beee4139
Revises: 13c1196f2ebc
Create Date: 2025-09-28 00:42:13.292420

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b290beee4139'
down_revision: Union[str, Sequence[str], None] = '13c1196f2ebc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('upload_files',
    sa.Column('file_name', sa.String(), nullable=False),
    sa.Column('url', sa.String(length=255), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('product_images',
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('image_id', sa.UUID(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['image_id'], ['upload_files.uuid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.uuid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.drop_table('product_tag')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_tag',
    sa.Column('product_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('tag_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('uuid', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.uuid'], name=op.f('product_tag_product_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.uuid'], name=op.f('product_tag_tag_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('product_id', 'tag_id', 'uuid', name=op.f('product_tag_pkey'))
    )
    op.drop_table('product_images')
    op.drop_table('upload_files')
    # ### end Alembic commands ###
