"""20250927_232312_modified_fields

Revision ID: e85f43f97311
Revises: b290beee4139
Create Date: 2025-09-28 04:23:12.898401

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'e85f43f97311'
down_revision: Union[str, Sequence[str], None] = 'b290beee4139'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('categories', 'name',
                    existing_type=sa.VARCHAR(),
                    type_=sa.JSON(),
                    existing_nullable=False,
                    postgresql_using="to_json(name::text)"
                    )
    op.alter_column('categories', 'description',
                    existing_type=sa.VARCHAR(),
                    type_=sa.JSON(),
                    existing_nullable=False,
                    postgresql_using="to_json(description::text)")
    op.drop_column('upload_files', 'file_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('upload_files', sa.Column('file_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.alter_column('categories', 'description',
                    existing_type=sa.JSON(),
                    type_=sa.VARCHAR(),
                    existing_nullable=False)
    op.alter_column('categories', 'name',
                    existing_type=sa.JSON(),
                    type_=sa.VARCHAR(),
                    existing_nullable=False)
    # ### end Alembic commands ###
